//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FasTeamLogic.FasdsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDao", Namespace="http://schemas.datacontract.org/2004/07/FasdsTeamSoap.DAO")]
    [System.SerializableAttribute()]
    public partial class UserDao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FasdsService.IDataContract")]
    public interface IDataContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContract/GetUsers", ReplyAction="http://tempuri.org/IDataContract/GetUsersResponse")]
        FasTeamLogic.FasdsService.UserDao[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContract/GetUsers", ReplyAction="http://tempuri.org/IDataContract/GetUsersResponse")]
        System.Threading.Tasks.Task<FasTeamLogic.FasdsService.UserDao[]> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContract/AddUser", ReplyAction="http://tempuri.org/IDataContract/AddUserResponse")]
        int AddUser(FasTeamLogic.FasdsService.UserDao user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContract/AddUser", ReplyAction="http://tempuri.org/IDataContract/AddUserResponse")]
        System.Threading.Tasks.Task<int> AddUserAsync(FasTeamLogic.FasdsService.UserDao user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContract/UpdateUser", ReplyAction="http://tempuri.org/IDataContract/UpdateUserResponse")]
        bool UpdateUser(FasTeamLogic.FasdsService.UserDao user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataContract/UpdateUser", ReplyAction="http://tempuri.org/IDataContract/UpdateUserResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserAsync(FasTeamLogic.FasdsService.UserDao user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataContractChannel : FasTeamLogic.FasdsService.IDataContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataContractClient : System.ServiceModel.ClientBase<FasTeamLogic.FasdsService.IDataContract>, FasTeamLogic.FasdsService.IDataContract {
        
        public DataContractClient() {
        }
        
        public DataContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FasTeamLogic.FasdsService.UserDao[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<FasTeamLogic.FasdsService.UserDao[]> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public int AddUser(FasTeamLogic.FasdsService.UserDao user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(FasTeamLogic.FasdsService.UserDao user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public bool UpdateUser(FasTeamLogic.FasdsService.UserDao user) {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserAsync(FasTeamLogic.FasdsService.UserDao user) {
            return base.Channel.UpdateUserAsync(user);
        }
    }
}
